<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mainSubjects = [
            // Grade 1 Main Subjects
            [
                'grade_id' => 1,
                'name' => 'الرياضيات',
                'code' => 'MATH-1',
                'success_rate' => 40,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'grade_id' => 1,
                'name' => 'اللغة العربية',
                'code' => 'AR-1',
                'success_rate' => 50,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'grade_id' => 1,
                'name' => 'العلوم',
                'code' => 'SCI-1',
                'success_rate' => 50,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Grade 2 Main Subjects
            [
                'grade_id' => 2,
                'name' => 'الرياضيات',
                'code' => 'MATH-2',
                'success_rate' => 40,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'grade_id' => 2,
                'name' => 'اللغة العربية',
                'code' => 'AR-2',
                'success_rate' => 50,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'grade_id' => 2,
                'name' => 'العلوم',
                'code' => 'SCI-2',
                'success_rate' => 50,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('main_subjects')->insert($mainSubjects);

        $subjects = [
            // Grade 1 Subjects
            [
                'name' => 'التحليل الرياضي',
                'main_subject_id' => 1,
                'code' => 'ANALYSIS-1',
                'full_mark' => 100,
                'homework_percentage' => 15,
                'oral_percentage' => 5,
                'activity_percentage' => 15,
                'quiz_percentage' => 25,
                'exam_percentage' => 40,
                'num_class_period' => 4,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'الجبر',
                'main_subject_id' => 1,
                'code' => 'ALGEBRA-1',
                'full_mark' => 100,
                'homework_percentage' => 20,
                'oral_percentage' => 10,
                'activity_percentage' => 10,
                'quiz_percentage' => 20,
                'exam_percentage' => 40,
                'num_class_period' => 4,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'اللغة العربية',
                'main_subject_id' => 2,
                'code' => 'AR-1',
                'full_mark' => 100,
                'homework_percentage' => 10,
                'oral_percentage' => 10,
                'activity_percentage' => 10,
                'quiz_percentage' => 20,
                'exam_percentage' => 50,
                'num_class_period' => 6,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'علم الأحياء',
                'main_subject_id' => 3,
                'code' => 'BIO-1',
                'full_mark' => 100,
                'homework_percentage' => 10,
                'oral_percentage' => 15,
                'activity_percentage' => 15,
                'quiz_percentage' => 20,
                'exam_percentage' => 40,
                'num_class_period' => 4,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'الفيزياء',
                'main_subject_id' => 3,
                'code' => 'PHY-1',
                'full_mark' => 100,
                'homework_percentage' => 10,
                'oral_percentage' => 10,
                'activity_percentage' => 20,
                'quiz_percentage' => 20,
                'exam_percentage' => 40,
                'num_class_period' => 4,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'الكيمياء',
                'main_subject_id' => 3,
                'code' => 'CHEM-1',
                'full_mark' => 100,
                'homework_percentage' => 10,
                'oral_percentage' => 10,
                'activity_percentage' => 20,
                'quiz_percentage' => 20,
                'exam_percentage' => 40,
                'num_class_period' => 4,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Grade 2 Subjects
            [
                'name' => 'التحليل الرياضي',
                'main_subject_id' => 4,
                'code' => 'ANALYSIS-2',
                'full_mark' => 100,
                'homework_percentage' => 15,
                'oral_percentage' => 5,
                'activity_percentage' => 15,
                'quiz_percentage' => 25,
                'exam_percentage' => 40,
                'num_class_period' => 4,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'الجبر',
                'main_subject_id' => 4,
                'code' => 'ALGEBRA-2',
                'full_mark' => 100,
                'homework_percentage' => 20,
                'oral_percentage' => 10,
                'activity_percentage' => 10,
                'quiz_percentage' => 20,
                'exam_percentage' => 40,
                'num_class_period' => 4,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'اللغة العربية',
                'main_subject_id' => 5,
                'code' => 'AR-2',
                'full_mark' => 100,
                'homework_percentage' => 10,
                'oral_percentage' => 10,
                'activity_percentage' => 10,
                'quiz_percentage' => 20,
                'exam_percentage' => 50,
                'num_class_period' => 6,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'علم الأحياء',
                'main_subject_id' => 6,
                'code' => 'BIO-2',
                'full_mark' => 100,
                'homework_percentage' => 10,
                'oral_percentage' => 15,
                'activity_percentage' => 15,
                'quiz_percentage' => 20,
                'exam_percentage' => 40,
                'num_class_period' => 4,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'الفيزياء',
                'main_subject_id' => 6,
                'code' => 'PHY-2',
                'full_mark' => 100,
                'homework_percentage' => 10,
                'oral_percentage' => 10,
                'activity_percentage' => 20,
                'quiz_percentage' => 20,
                'exam_percentage' => 40,
                'num_class_period' => 4,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'الكيمياء',
                'main_subject_id' => 6,
                'code' => 'CHEM-2',
                'full_mark' => 100,
                'homework_percentage' => 10,
                'oral_percentage' => 10,
                'activity_percentage' => 20,
                'quiz_percentage' => 20,
                'exam_percentage' => 40,
                'num_class_period' => 4,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('subjects')->insert($subjects);
    }
}
